name: Print Software Versions   

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   

jobs:
  PrintLanguageVersions:   # Job для мов програмування
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Java Version
        run: java --version

      - name: Print Node Version
        run: node --version

      - name: Print Python Version
        run: python --version

  PrintDBMSVersions:       # Job для СКБД
    runs-on: ubuntu-latest
    needs: PrintLanguageVersions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print PostgreSQL Version
        run: psql --version

      - name: Print MySQL Version
        run: mysql -V

      - name: Print MongoDB Version
        run: mongod --version
